site_name: Docs manager

repo_url: https://github.com/jdev-org/docs-manager-front
repo_name: docs-manager-front

docs_dir: docs
edit_uri: edit/main/docs/

theme:
  language: fr
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  logo: images/georchestra-logo-white.svg
  favicon: images/favicon.ico
  name: material

extra:
  version:
    provider: mike

  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:psc@georchestra.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/georchestra
    - icon: fontawesome/brands/github
      link: https://github.com/georchestra
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/georchestra?hl=en
    - icon: fontawesome/brands/dev
      link: https://groups.google.com/group/georchestra-dev?hl=fr
    - icon: fontawesome/regular/comments
      link: https://kiwiirc.com/client/irc.libera.chat/georchestra
copyright: '© 2023 - geOrchestra'

extra_css:
    - css/extra.css

extra_javascript:
    - assets/custom_versions.js

# arborescence de 1er et 2e niveau à gérer ici
# Ces entrées correspondent au modèle de documentation

nav:
    - Accueil: index.md 
    - Guide utilisateur:
        - Sommaire: guide_utilisateur/index.md
        - Prendre en main: guide_utilisateur/00_prise_en_main.md
        - Fenêtre principale: guide_utilisateur/01_fenetre_principale.md
        - Ajouter un document: guide_utilisateur/ajout.md
    - Guide technique - Backend:
        - Sommaire: tech_backend/index.md
        - Installer:
            - tech_backend/installer/index.md
        - Développer:
            - tech_backend/developper/index.md
        - Configuration:
            - tech_backend/configurer/index.md
    - Guide technique - extension:
        - Sommaire: tech_module/index.md
        - Configurer:
            - tech_module/config/index.md
        - Installer:
            - tech_module/installer/index.md
        - Développer:
            - tech_module/developper/index.md
    - Guide technique - documentation:
        - Sommaire: tech_doc/index.md
        - Maintenir: tech_doc/update/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
    - search
    - callouts
    - toc-md:
        toc_page_title: Contents
        toc_page_description: Summary of the section
        header_level: 3
        pickup_description_meta: false
        pickup_description_class: false
        output_path: tableofcontent.md
        output_log: true
        ignore_page_pattern: index.md
        remove_navigation_page_pattern: index.md
        template_dir_path: custom_template
    - git-revision-date-localized:
        enable_creation_date: true


# TODO Documenter comment simplifier l'arborescence pour un petit projet
